### ISSUE TITLE
Add a website

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Women-Communities#12]
I just need a HTML type website, hosted on Heroku.

- Sign up in an [Heroku](https://id.heroku.com/login) account.
- Deploy the website.
- Take credentials from me.
- Deploy on my Heroku account.

**Comment by mridubhatnagar** [comment]
![Screenshot from 2019-05-04 22-04-05](https://user-images.githubusercontent.com/16894718/57182068-c3d40280-6eb8-11e9-8f3a-1bbf95b28ee2.png)

**Comment by mridubhatnagar** [comment]
I am getting a merge conflict in README.md. I resolved the merge conflict. Did a git add followed by git commit. Repush the changes. But, on squashing again same errors come.
