### ISSUE TITLE
Create a table in the readme and separate the communities

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Women-Communities#17]
| Women in Technology Communities | Women in E&M Communities |  Women in T&M Communities | Women in Products Communities | Women in Mathematics Communities  | Women in S&M Communities | Women who code communities | Women in Consulting Communities | Generic Women Communities |
|---|---|---|---|---|---|---|---|---|
|   |   |   |   |   |  | | | |

**Comment by keshavg2** [comment]
Hi @tapaswenipathak can you please help me. I can give the name of community in which row these name I will add it? 
Women Who Go
She codes for change
She codes Africa
Pehia Foundation
WAAW Foundation
Connecting African Women in STEM
DjangoGirls
ProjectCSgirls
SHEROES

**Comment by tapaswenipathak** [comment]
Please find inline.

On Fri, May 10, 2019 at 10:32 PM Keshav Gupta <notifications@github.com> wrote:
>
> Hi @tapaswenipathak can you please help me. I can give the name of community in which row these name I will add it?
> Women Who Go - Women who code communities
> She codes for change - Women who code communities
> She codes Africa - Women who code communities
> Pehia Foundation - Women in T&M Communities
> WAAW Foundation - Generic Women Communities
> Connecting African Women in STEM - Generic Women Communities
> DjangoGirls - Women who code communities
> ProjectCSgirls - Generic Women Communities
> SHEROES - Generic Women Communities
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by keshavg2** [comment]
Thanks @tapaswenipathak
