### ISSUE TITLE
Add theme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Women-Communities#22]
I have added a [theme](https://github.com/tapaswenipathak/Theme).

- Install using `npm i list-theme`.
- Add the information present in [index.html](https://github.com/tapaswenipathak/Women-Communities/blob/master/index.html) in the theme's [index.html](https://github.com/tapaswenipathak/Theme/blob/master/index.html#L6-L42) 
- Deploy on a Heroku App.
- Take the credentials from me.
- Deploy in my Heroku account.

**Comment by keshavg2** [comment]
Hi @tapaswenipathak can I work upon this?

**Comment by tapaswenipathak** [comment]
On Thu, May 9, 2019 at 10:33 AM Keshav Gupta <notifications@github.com> wrote:
>
> Hi @tapaswenipathak can I work upon this?

Sure!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by keshavg2** [comment]
Thanks @tapaswenipathak

**Comment by keshavg2** [comment]
I have add the `index.html` in the theme `index.html` but how I see my changes?

**Comment by tapaswenipathak** [comment]
On Thu, May 9, 2019 at 11:37 AM Keshav Gupta <notifications@github.com> wrote:
>
> I have add the index.html in the theme index.html but how I see my changes?

Just opening index.html file should show the theme.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by keshavg2** [comment]
when I add the index.html  in to index.html file in theme but this will show a theme not shown a table of women communities.

**Comment by tapaswenipathak** [comment]
On Thu, May 9, 2019 at 1:54 PM Keshav Gupta <notifications@github.com> wrote:
>
> But how I see my table when I add in to it.

After you add the theme if you open index.html you should see the
theme enabled that's the task. Feel free getting on a call if you get
stuck for long https://calendly.com/tapaswenipathak.

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by prateekj117** [comment]
@17bcs029 Are you still on this issue? If not, I would like to take over.

**Comment by keshavg2** [comment]
Hi @prateekj117 sure you will work upon it.

**Comment by prateekj117** [comment]
@tapaswenipathak So I have cloned the theme repo and started the server locally using gulp. Everything seems to work fine to this point. Can you tell me what other things do I need to do next?

**Comment by tapaswenipathak** [comment]
On Sun, May 12, 2019 at 4:17 PM Prateek Jain <notifications@github.com> wrote:
>
> @tapaswenipathak So I have cloned the theme repo and started the server locally using gulp. Everything seems to work fine to this point. Can you tell me what other things do I need to do next?

You should add the code required for enabling the theme in this
repository, if you get stuck for long, feel free in letting me know
https://calendly.com/tapaswenipathak.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

Tapasweni

**Comment by prateekj117** [comment]
@tapaswenipathak So I should also add a table in the theme to display the list in the Internship.

**Comment by prateekj117** [comment]
@tapaswenipathak This website has some added files for Django, will I have to add the theme keeping the app django centric, or should I migrate to gulp and make it a purely static site like all other websites?

**Comment by tapaswenipathak** [comment]
On Thu, May 16, 2019 at 9:40 PM Prateek Jain <notifications@github.com> wrote:
>
> @tapaswenipathak This website has some added files for Django, should I add the theme keeping the app django centric, or should I migrate  gulp and make it a purely static site like all other websites?

Please add the code from
https://github.com/tapaswenipathak/Open-Source-Programs. Let me know
if you have any questions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
