### ISSUE TITLE
Add pr template 

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Women-Communities#28]
Any addition should be written in index.html.

**Comment by sourabhpruthi10** [comment]
@tapaswenipathak actually for pr template we have a separate file called as pull_request_template and i am not able to understand how to add in index.html

**Comment by tapaswenipathak** [comment]
On Fri, May 10, 2019 at 1:03 PM Sourabh Pruthi <notifications@github.com> wrote:
>
> @tapaswenipathak actually for pr template we have a separate file called as pull_request_template and i am not able to understand how to add in index.html

PR template should have



- [ ] Women Community is added in README.md file in correct table
- [ ] Women Community is added in index.html in correct table
- [ ] Website tested on a deployment

>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
